// Deprecated — re-exports from new location for backward compatibility.
export {
  walkTree,
  findNodeById,
  findParentOf,
  addWidgetToRow,
  removeNode,
  moveNode,
  setNodeSizing,
  setNodeSpan,
  addRow,
  removeEmptyRows,
  wrapInContainer,
  unwrapContainer,
  wrapInZStack,
  addWidgetToZStack,
  setNodeStyle,
  setNodeCondition,
  setNodeRepeat,
  balanceCraftRow,
} from "./engine/layoutEngine.js";
